### ISSUE TITLE
Adjust shebang to not be hard coded to /bin/bash

### ISSUE THREAD

**Issue by spion06** [pkopriv2/bashum#3]
~/.bashum/bin/griswold currently has it's shebang hard coded to /bin/bash. This causes issues if your system bash isn't version 4.2. This should be adjusted to /usr/bin/env bash

**Comment by pkopriv2** [comment]
Fixed: https://github.com/pkopriv2/bashum/commit/c68135ffbb7d15f83de099750b60c82266c22d31
