### ISSUE TITLE
GNU-Tar isn't needed for mac.

### ISSUE THREAD

**Issue by JakeLaCombe** [pkopriv2/bashum#6]
I was running the installation instructions, and found that standard tar is sufficient enough to install this script. I recommend removing that section for mac installation, as you're basically renaming tar to tar-bsd, which will error out several of your bash scripts that download a tar.gz file.

If I'm missing something, let me know.

**Comment by pkopriv2** [comment]
Gnu-tar is needed to build bashums.  Gnu-tar is a prereq so that anything that would need to tar/untar archives has a valid installation of tar.  As long as the prereq is satisfied, nothing should be affected.
